/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvaluateRouteImport } from './routes/evaluate'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GenerateQuizRouteImport } from './routes/generate-quiz'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PdfChatRouteImport } from './routes/pdf-chat'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SummarizerRouteImport } from './routes/summarizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluateRoute = EvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateQuizRoute = GenerateQuizRouteImport.update({
  id: '/generate-quiz',
  path: '/generate-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfChatRoute = PdfChatRouteImport.update({
  id: '/pdf-chat',
  path: '/pdf-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerRoute = SummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/explore': typeof ExploreRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate-quiz': typeof GenerateQuizRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pdf-chat': typeof PdfChatRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/explore': typeof ExploreRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate-quiz': typeof GenerateQuizRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pdf-chat': typeof PdfChatRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/evaluate': typeof EvaluateRoute
  '/explore': typeof ExploreRoute
  '/flashcards': typeof FlashcardsRoute
  '/generate-quiz': typeof GenerateQuizRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/pdf-chat': typeof PdfChatRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summarizer': typeof SummarizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/evaluate'
    | '/explore'
    | '/flashcards'
    | '/generate-quiz'
    | '/learn'
    | '/login'
    | '/pdf-chat'
    | '/planner'
    | '/quiz'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/summarizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/evaluate'
    | '/explore'
    | '/flashcards'
    | '/generate-quiz'
    | '/learn'
    | '/login'
    | '/pdf-chat'
    | '/planner'
    | '/quiz'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/summarizer'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/evaluate'
    | '/explore'
    | '/flashcards'
    | '/generate-quiz'
    | '/learn'
    | '/login'
    | '/pdf-chat'
    | '/planner'
    | '/quiz'
    | '/results'
    | '/signup'
    | '/sitemap.xml'
    | '/summarizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  EvaluateRoute: typeof EvaluateRoute
  ExploreRoute: typeof ExploreRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GenerateQuizRoute: typeof GenerateQuizRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PdfChatRoute: typeof PdfChatRoute
  PlannerRoute: typeof PlannerRoute
  QuizRoute: typeof QuizRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SummarizerRoute: typeof SummarizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluate': {
      id: '/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof EvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-quiz': {
      id: '/generate-quiz'
      path: '/generate-quiz'
      fullPath: '/generate-quiz'
      preLoaderRoute: typeof GenerateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-chat': {
      id: '/pdf-chat'
      path: '/pdf-chat'
      fullPath: '/pdf-chat'
      preLoaderRoute: typeof PdfChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer': {
      id: '/summarizer'
      path: '/summarizer'
      fullPath: '/summarizer'
      preLoaderRoute: typeof SummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  EvaluateRoute: EvaluateRoute,
  ExploreRoute: ExploreRoute,
  FlashcardsRoute: FlashcardsRoute,
  GenerateQuizRoute: GenerateQuizRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PdfChatRoute: PdfChatRoute,
  PlannerRoute: PlannerRoute,
  QuizRoute: QuizRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SummarizerRoute: SummarizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
